version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-provisioned-concurrency"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xjrnenuuayt3"
s3_prefix = "lambda-provisioned-concurrency"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
