AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda.provisioned.concurrency

  Sample SAM Template for lambda.provisioned.concurrency

Globals:
  Function:
    Runtime: go1.x
    Tracing: Active
    Timeout: 15

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  NormalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: normal/
      Handler: normal
      Events:
        HelloAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /normal
            Method: GET

  ProvisionedConcurrencyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: provisioned/
      Handler: provisioned
      AutoPublishAlias: live #starts provision concurrency config for lambda
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 10 #ends provision concurrency config for lambda
      Events:
        HelloAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /provisioned
            Method: GET

Outputs:
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
