AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda.destinations

  Sample SAM Template for lambda.destinations

Globals:
  Function:
    Timeout: 5

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: hello-world
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref OnSuccessFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref OnFailureFunction

  OnSuccessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: success/
      Handler: success
      Runtime: go1.x

  OnFailureFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: failure/
      Handler: failure
      Runtime: go1.x

  EventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref HelloWorldFunction
      Qualifier: "$LATEST"
      MaximumEventAgeInSeconds: 600
      MaximumRetryAttempts: 0
      DestinationConfig:
        OnSuccess:
          Destination: !GetAtt OnSuccessFunction.Arn
        OnFailure:
          Destination: !GetAtt OnFailureFunction.Arn

Outputs:
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
