version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eventbridge-sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xjrnenuuayt3"
s3_prefix = "eventbridge-sample"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
