AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Template that glue api, messeging and events nested stack

Resources:
  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: api.template.yaml
    DependsOn: Messeging
  Messeging:
    Type: AWS::Serverless::Application
    Properties:
      Location: messeging.yaml
