AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  eventbridge

  Sample SAM Template for eventbridge

Globals:
  Function:
    Runtime: go1.x
    Timeout: 25
    MemorySize: 128

Resources:
  OrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: orders/
      Handler: orders
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
          Environment:
      Variables:
        EVENT_BUS_NAME: ""

  ForecastFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: forecast/
      Handler: forecast
      Runtime: go1.x
      Tracing: Active

Outputs:
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  OrdersFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt OrdersFunction.Arn
  OrdersFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt OrdersFunctionRole.Arn
